name: lerna-version
description: Use Lerna version to increment, tag and create a changelog for all or individual packages
inputs:
  packages:
    description: The comma or newline delimited list of packages to bump (* or all)
    required: true
  exclude:
    description: The comma or newline delimited list of packages to exclude
    required: false
  log-level:
    description: The logging level for Lerna version command
    required: false
    default: info
outputs:
  GIT:
    description: Changed packages for pushing to a remote git repo (eg GitHub Actions)
  KUBE_JOB:
    description: Changed Kubernetes cronjobs (comma separated)
  KUBE_DEPLOYMENT:
    description: Changed Kubernetes deployments (comma separated)
  LAMBDA:
    description: Changed AWS Lambda functions (comma separated)
  MAVEN:
    description: Change Maven jars (comma separated)
  NPM:
    description: Changed npm packages (comma separated)
  S3:
    description: Changed S3 web asset bundles (comma separated)
runs:
  using: node12
  main: index.js
  post: post/index.js
  post-if: success()
