name: version
description: Use Lerna version to increment, tag and create a changelog for all or individual packages
inputs:
  packages:
    description: The comma or newline delimited list of packages to bump (* for all)
    required: true
  prod-branch:
    description: The branch for production releases
    required: false
    default: 'prod'
  dry-run:
    description: Bump version and tag but don't push
    required: false
    default: 'false'
  log-level:
    description: The logging level for Lerna version command
    required: false
    default: 'info'
runs:
  using: 'node12'
  main: 'dist/index.js'
