name: s3-deploy
description: Upload static assets to the S3 website
inputs:
  app:
    description: Client app name or comma separated list of apps
    required: true
  staging-bucket-prefix:
    description: S3 artifact bucket prefix excluding env suffix [dev,qa,prod]
    required: false
    default: 'rss-config-'
  website:
    description: S3 website. Defaults to the "branch-env + website-suffix".
    required: false
  website-suffix:
    description: S3 website suffix excluding env prefix [dev,qa,prod]. Ignored if website is defined.
    required: false
    default: 'riskandsafety.com'
  dry-run:
    description: Preview the S3 delete and put commands
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'index.js'
