name: S3 Deploy
description: Upload static assets to the S3 website
inputs:
  app:
    description: Client app name or comma separated list of apps
    required: true
  env:
    description: Override the target env [dev,qa,prod,hc]. Defaults to the branch name.
    required: false
  staging-bucket:
    description: S3 artifact bucket
    required: false
    default: rss-artifact
  website:
    description: S3 website. Defaults to the "branch-env + website-suffix".
    required: false
  website-suffix:
    description: S3 website suffix excluding env prefix [dev,qa,prod,hc]. Ignored if website is defined.
    required: false
    default: riskandsafety.com
  website-dir:
    description: S3 directory to prepend when putting files.
    required: false
    default: ''
  zip-file:
    description: Path to the zip file. If not provided it will pull the staged zip from S3.
    required: false
    default: "false"
  stage-next-zip-file:
    description: Indicates if the zip file should be staged for the next environment.
    required: false
    default: "true"
outputs:
  url:
    description: URL to the deployed version.json file
runs:
  using: node12
  main: index.js
  post: post/index.js
  post-if: success()
