name: S3 Deploy
description: Upload static assets to the S3 website
inputs:
  app:
    description: Client app name or comma separated list of apps
    required: true
  env:
    description: Override the target env [dev,qa,prod,hc]. Defaults to the branch name.
    required: false
  src-env:
    description: The artifact name to deploy. Defaults to the PR src branch.
    required: false
  staging-bucket:
    description: S3 artifact bucket
    required: false
    default: rss-artifact
  website:
    description: S3 website. Defaults to the "branch-env + website-suffix".
    required: false
  website-suffix:
    description: S3 website suffix excluding env prefix [dev,qa,prod,hc]. Ignored if website is defined.
    required: false
    default: riskandsafety.com
  dry-run:
    description: Preview the S3 delete and put commands
    required: false
    default: "false"
runs:
  using: node12
  main: index.js
  post: post/index.js
  post-if: success()
