name: actions-dist
description: Push compiled GitHub Action assets (eg dist/, action.yml) to different git repository
inputs:
  repo:
    description: Git repository for the compiled assets
    required: true
  ssh-deploy-key:
    description: SSH key for writing to the git repository
    required: false
  dry-run:
    description: Don't push to git repository
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
