name: Docker Stage
description: Build and push Docker image for staging
inputs:
  username:
    description: Username for the repo
    required: true
  password:
    description: Password/token for the repo
    required: true
  app:
    description: App name or comma separated list of apps to stage
    required: true
  src-tag-prefix:
    description: If provided uses the latest image with this prefix instead of doing a docker build
    required: false
  path:
    description: Docker build directory to build from instead of tagging an existing image.
    required: false
    default: '.'
  registry:
    description: Docker registry
    required: false
    default: docker.pkg.github.com
runs:
  using: node12
  main: index.js
