name: docker-stage
description: Build and push Docker image for staging and caching
inputs:
  username:
    description: Username for the repo
    required: true
  password:
    description: Password/token for the repo
    required: true
  app:
    description: App name or comma separated list of apps to stage
    required: true
  src-tag-prefix:
    description: If provided uses the latest image with this prefix instead of doing a docker build
    required: false
  path:
    description: Docker build directory (default '.')
    required: false
    default: '.'
  repo:
    description: Repository "owner/name" or url. Defaults to the repo calling this action.
    required: false
  registry:
    description: Docker registry
    required: false
    default: docker.pkg.github.com
runs:
  using: 'node12'
  main: 'index.js'
