name: Docker Stage
description: Build and push Docker image for staging
inputs:
  username:
    description: Username for the repo
    required: true
  password:
    description: Password/token for the repo
    required: true
  app:
    description: App name
    required: true
  docker-name:
    description: Docker image name if different from the app name
    required: false
  path:
    description: Docker build directory.
    required: false
    default: '.'
  registry:
    description: Docker registry
    required: false
    default: docker.pkg.github.com
outputs:
  image:
    description: The Docker image name
runs:
  using: node12
  main: index.js
