name: Docker Pull
description: Pull previously built image and compare file hash for cache hit.
inputs:
  username:
    description: Username for the repo
    required: true
  password:
    description: Password/token for the repo
    required: true
  app:
    description: App name
    required: true
  file-hash:
    description: File hash to compare to the Docker 'fileHash' label to determine a cache hit
    required: false
  registry:
    description: Docker registry
    required: false
    default: docker.pkg.github.com
outputs:
  image:
    description: The Docker image name
  found:
    description: True if the Docker image exists
  cache-hit:
    description: True if the file hash matches the Docker 'fileHash' label
runs:
  using: node12
  main: index.js
