name: Label Changed Packages
description: Adds pull request labels for monorepo packages that have changed since the last merge or tag
inputs:
  GITHUB_TOKEN:
    description: The GitHub Action token
    required: true
  diff-by:
    description: Calculate changes by either comparing the branches or HEAD with the most recent tag. Options are [branch,tag]
    required: false
    default: branch
  prefix:
    description: The prefix to use for labels
    required: false
    default: "deploy:"
runs:
  using: node12
  main: index.js
