name: Docker Release
description: Docker build and push. If tagged for deploy, Flux will pick up the new image (eg prod-1234567) after a few minutes.
inputs:
  username:
    description: Username for the repo
    required: true
  password:
    description: GitHub Token or Personal Access Token for the GitHub Container Registry ghcr.io
    required: true
  GITHUB_TOKEN:
    description: GitHub Token for pruning old Docker images from GitHub Docker Package Registry. TODO remove once moved over to Container Registry
    required: false
  app:
    description: App name
    required: true
  docker-name:
    description: Docker image name if different from the app name
    required: false
  tag-prefix:
    description: Image tag prefix that Fluxcd will look for (eg 'glob:dev-*'). Defaults to the env [dev,qa,prod,hc]
    required: false
  tag-suffix:
    description: Image tag prefix for Fluxcd to check for newest. Defaults to ISO basic date format YYYYMMDDThhmmss
    required: false
  deploy:
    description: Indicates the Docker image should be tagged for deployment (eg 'prod-12345678')
    required: false
    default: 'true'
  stage-next-image:
    description: Indicates the Docker image should be staged for the next environment (eg RC_qa)
    required: false
    default: 'true'
  path:
    description: Docker build directory. If not provided, the staged Docker image will be tagged for deployment.
    required: false
  labels:
    description: Additional labels to add to the Docker image. Already includes 'created' and 'commit'.
    required: false
  registry:
    description: Docker registry
    required: false
    default: docker.pkg.github.com
outputs:
  image:
    description: The Docker image name
runs:
  using: node12
  main: index.js
  post: post/index.js
  post-if: success()
