name: Docker Release
description: Add docker tag for Flux to pickup the new image (eg prod-1234567, 1.0.1)
inputs:
  username:
    description: Username for the repo
    required: true
  password:
    description: Password/token for the repo
    required: true
  app:
    description: App name or comma separated list of apps to tag for release
    required: true
  tag-prefix:
    description: Image tag prefix that Flux will look for (eg 'glob:dev-*'). Defaults to the env [dev,qa,prod,hc]
    required: false
  path:
    description: Docker build directory to build from instead of tagging an existing image. Only appies to a single app.
    required: false
  registry:
    description: Docker registry
    required: false
    default: docker.pkg.github.com
runs:
  using: node12
  main: index.js
  post: post/index.js
  post-if: success()
