name: Docker Release
description: Docker build and push. If tagged for deploy, Flux will pick up the new image (eg prod-1234567) after a few minutes.
inputs:
  username:
    description: Username for the repo
    required: true
  password:
    description: GitHub Token or Personal Access Token for the GitHub Container Registry ghcr.io
    required: true
  app:
    description: App name
    required: true
  docker-name:
    description: Docker image name if different from the app name
    required: false
  file:
    description: Path to the Dockerfile
    required: false
  tag-prefix:
    description: Image tag prefix that Fluxcd will look for (eg 'glob:dev-*'). Defaults to the env [dev,qa,prod,hc]
    required: false
  deploy:
    description: Indicates the Docker image should be tagged for deployment (eg 'prod-12345678')
    required: false
    default: 'true'
  stage-next-image:
    description: Indicates the Docker image should be staged for the next environment (eg RC_qa)
    required: false
    default: 'true'
  path:
    description: Docker build directory. If not provided, the staged Docker image will be tagged for deployment.
    required: false
  labels:
    description: Additional labels to add to the Docker image. Already includes 'created' and 'commit'.
    required: false
  registry:
    description: Docker registry
    required: false
    default: docker.pkg.github.com
  buildArg:
    description: Docker build args. Provide the comma/space separated string (eg a_variable=a_value,b_variable=b_value)
    required: false
outputs:
  image:
    description: The Docker image name
runs:
  using: node16
  main: index.js
