name: kube-status
description: Watch the deployment status using FluxCD and Kubernetes APIs
inputs:
  app:
    description: App name or comma separated list of apps
    required: true
  docker-name:
    description: Docker image name if different from the app name
    required: false
  namespace:
    description: Kubernetes namespace for the app
    required: false
    default: apps
  kind:
    description: Kubernetes manifest type (daemonset or deployment)
    required: false
    default: deployment
  tag-prefix:
    description: Image tag prefix that Flux will look for (eg 'glob:dev-*'). Defaults to the branch-env [dev,qa,prod,hc]
    required: false
  cluster-name:
    description: Kubernetes cluster name
    required: false
    default: rss
  registry:
    description: Docker registry
    required: false
    default: docker.pkg.github.com
  kibana-host:
    description: Kibana host where the logs reside
    required: false
    default: https://logs.risksafety.io
  retries:
    description: Number of times to retry Flux release
    required: false
    default: "5"
runs:
  using: node12
  main: index.js
