name: Label Changed Packages
description: Adds pull request labels for monorepo packages that have changed between branches or tags
inputs:
  GITHUB_TOKEN:
    description: The GitHub Action token
    required: true
  diff-by:
    description: Determine what has changed by either comparing against the next branch or the most recent release tag. Options are [branch,tag]
    required: false
    default: branch
  dry-run:
    description: Indicates that the labels should be calculated and output but not pushed to the pull request
    required: false
    default: "false"
  prefix:
    description: Label prefix
    required: false
    default: "deploy:"
outputs:
  labels:
    description: Comma separated list of app labels
runs:
  using: node12
  main: index.js
