name: s3-stage
description: Upload zip to S3 config bucket for staging
inputs:
  action:
    description: Either "upload" or "download" the zip to S3 staging
    required: false
    default: upload
  app:
    description: App or Lambda function name
    required: true
  context:
    description: Webapp context path (eg app-path/) to add to the zip
    required: false
    default: ''
  build-dir:
    description: Path to the source code directory
    required: true
  staging-bucket-prefix:
    description: The S3 config bucket prefix excluding env suffix (eg dev, qa, prod)
    required: false
    default: 'rss-config-'
runs:
  using: 'node12'
  main: 'index.js'
