name: S3 Stage
description: Upload or promote zip to S3 artifact bucket for staging
inputs:
  command:
    description: Commands are "upload" or "promote" to copy the zip to the next env.
    required: false
    default: upload
  app:
    description: App name or Lambda name. Can be a comma deliminted list for the "promote" command.
    required: true
  context:
    description: Webapp context path (eg app-path/) to add to the zip, for "upload" command
    required: false
    default: ""
  build-dir:
    description: Path to the source code directory for "upload" command
    required: true
  staging-bucket:
    description: S3 artifact bucket
    required: false
    default: rss-artifact
runs:
  using: node14
  main: index.js
