name: Pull Request Package Labeler
description: Dynamically label pull requests affecting packages in a monorepo / workspace
inputs:
  GITHUB_TOKEN:
    description: The GitHub Action token
    required: true
  workspace:
    description: Lerna folder to looking for changed files
    required: false
    default: packages
  prefix:
    description: The prefix to use for labels
    required: false
    default: "deploy:"
runs:
  using: node12
  main: index.js
