name: branch-env
description: For the current branch, export the AWS environment as the var name. Defaults to "dev" for feature branches.
inputs:
  env-list:
    description: List of branches that match the AWS environments. Falls back to "dev" if none match.
    required: false
    default: qa,prod
  var-name:
    description: Name of the env variable to export
    required: true
runs:
  using: 'node12'
  main: 'index.js'
