name: Kube CI
description: Copies Kubernetes yaml files in git repository to a new namespace based on th git branch
inputs:
  repo:
    description: Kubernetes manifest git repository
    required: true
  ssh-deploy-key:
    description: SSH key for writing to the Kubernetes manifest git repository
    required: false
  repo-branch:
    description: Fluxcd Kubernetes manifest git repository branch
    required: false
    default: "master"
  src-dir:
    description: Kubernetes manifest git repository directory to pull from
    required: true
    default: "dev/apps/"
  dest-dir:
    description: Kubernetes manifest git repository directory for the new namespace (defaults to sibling directory of src-dir named {namespace})
    required: false
  namespace:
    description: Destination namespace and subdomain (eg branch name)
    required: true
  website-suffix:
    description: Website suffix excluding branch subdomain
    required: true
  s3-bucket:
    description: S3 bucket for website assets
    required: true
  files:
    description: List of base files or directories to copy over before the labels.
    required: false
  labels:
    description: "Comma delimited list or serialized JSON array (eg [{ label: 'app-a'}, ...])"
    required: false
  aws-cognito-client-id:
    description: AWS Cognito client ID
    required: false
  aws-cognito-user-pool-id:
    description: AWS Cognito user pool ID
    required: false
  dry-run:
    description: Don't push to git repository
    required: false
    default: "false"
runs:
  using: node12
  main: index.js
