name: lerna-group-deploy-types
description: Group Lerna packages by package.json deploy type
inputs:
  packages:
    description: "Comma delimited list or serialized JSON array of packages (eg [{ name: 'deploy:app-a'}, ...])"
    required: true
  prefix:
    description: Package name prefix to ignore packages that should not be deployed
    required: false
    default: 'deploy:'
outputs:
  GIT:
    description: Changed packages for pushing to a remote git repo (eg GitHub Actions)
  KUBE_JOB:
    description: Changed Kubernetes cronjobs (comma separated)
  KUBE_DEPLOYMENT:
    description: Changed Kubernetes deployments (comma separated)
  LAMBDA:
    description: Changed AWS Lambda functions (comma separated)
  MAVEN:
    description: Change Maven jars (comma separated)
  NPM:
    description: Changed npm packages (comma separated)
  S3:
    description: Changed S3 web asset bundles (comma separated)
runs:
  using: node14
  main: index.js
