name: lambda-deploy
description: Deploy the S3 zip files to AWS Lambda
inputs:
  function:
    description: Function name or comma separated list of functions
    required: true
  staging-bucket-prefix:
    description: The S3 config bucket prefix excluding env suffix (eg dev, qa, prod)
    required: false
    default: 'rss-config-'
runs:
  using: 'node12'
  main: 'index.js'
