name: lambda-deploy
description: Deploy the S3 zip files to AWS Lambda
inputs:
  function:
    description: Function name or comma separated list of functions
    required: true
  staging-bucket-prefix:
    description: S3 artifact bucket prefix excluding env suffix [dev,qa,prod]
    required: false
    default: 'rss-config-'
  env:
    description: Target deployment env [dev,qa,prod]. Defaults to using the destination branch name.
    required: false
runs:
  using: 'node12'
  main: 'index.js'
