name: Actions Release
description: Push compiled GitHub Action assets (eg action.yml) to different git repository
inputs:
  repo:
    description: Remote git repo for the compiled assets
    required: true
  build-dir:
    description: Directory containing the compiled assets
    required: false
    default: 'build/'
  ssh-deploy-key:
    description: SSH key for writing to the git repository
    required: false
  pre-release:
    description: Compiled assets should be pushed to a matching feature branch in the remote git repo
    required: false
    default: 'false'
  dry-run:
    description: Don't push to git repository
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'index.js'
