name: Find package.json by labels
description: Returns a modified version of the Lerna package.json files using the PR labels
inputs:
  GITHUB_TOKEN:
    description: The GitHub Action token
    required: false
    default: ${{ github.token }}
  include:
    description: Labels to use instead of querying the current pull request
    required: false
  package-json-keys:
    description: Package.json keys to include in the output
    required: false
    default: label,name,location,config,scripts
outputs:
  packages:
    description: Serialized JSON array of modified package.json files.
runs:
  using: node12
  main: index.js
