name: Find package.json by labels
description: Returns a modified version of the Lerna package.json files using the PR labels
inputs:
  GITHUB_TOKEN:
    description: The GitHub Action token
    required: false
    default: ${{ github.token }}
  include:
    description: Additional labels to add or use if not a pull request
    required: false
  package-json-keys:
    description: Package.json keys to include in the output
    required: false
    default: label,name,location
outputs:
  packages:
    description: Serialized JSON array of trimmed down package.json files
runs:
  using: node16
  main: index.js
