name: Docker Prune
description: GitHub Action to delete container versions, grouped by tag prefix
inputs:
  token:
    description: Personal Access Token with scopes `packages:read` and `packages:delete` and write permissions to the container
    required: true
  app:
    description: Name of the container to prune
    required: true
  tag-prefixes:
    description: Tag prefixes to group images by when determining keep-last. Prefixes should in descending order of precedence
    required: true
  older-than:
    description: Minimum age in days of container versions to prune
    required: false
    default: '14'
  keep-last:
    description: Count of most recent, matching containers to exclude from pruning
    required: false
    default: '10'
  untagged:
    description: Whether untagged container versions should be pruned
    required: false
    default: 'true'
runs:
  using: node12
  main: index.js
